version: '3'
services:
  mosquitto:
    image: 'eclipse-mosquitto:latest'
    container_name: mqtt_server
    restart: always
    ports:
      - '1883:1883'
    volumes:
      - ./shared_container_volumes/mosquitto/data:/mosquitto/data
      - ./shared_container_volumes/mosquitto/log:/mosquitto/log
      - ./shared_container_volumes/mosquitto/config:/mosquitto/config

