version: '3.7'
services:
  mosquitto:
    image: 'eclipse-mosquitto:latest'
    container_name: mqtt_server
    restart: always
    network_mode: host
    # ports:
    #   - "1883:1883"
    volumes:
      - ./shared_container_volumes/mosquitto/data:/mosquitto/data
      - ./shared_container_volumes/mosquitto/log:/mosquitto/log
      - ./shared_container_volumes/mosquitto/config:/mosquitto/config
  iobroker:
    image: 'buanet/iobroker:latest-v6'
    container_name: iobroker
    restart: always
    network_mode: host
    # ports:
    #   - "8081:8081"
    #   - "8082:8082"
    volumes:
      - ./shared_container_volumes/iobroker:/opt/iobroker

